# Generated by Django 5.2 on 2025-04-24 12:04

import core.media_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Tech'), ('Lifestyle', 'Life'), ('Education', 'Edu'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=core.media_storage.MediaStorage(), upload_to='post_images/'),
        ),
    ]
